---
title: "README"
author: "Rebecca Batstone"
date: "`r format(Sys.Date())`"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Data analyses for Batstone et al (AJB submission)

Abstract:

The ecological outcomes of mutualism are well known to shift across abiotic or biotic environments, but few studies have addressed how different environments impact the intensity of selection on or the expression of genetic variance in key mutualism-related traits. We planted 30 maternal lines of the legume *Medicago lupulina* in four field common gardens and compared our measures of selection on and genetic variance in nodulation, a key trait reflecting legume investment in the symbiosis, with those from a previous greenhouse experiment using the same 30 *M. lupulina* lines. We found that both the mean and genetic variance for nodulation was much greater in the greenhouse than in the field and that the magnitude and form of selection on nodulation significantly differed across environments. We also found significant genotype-by-environment (G x E) effects for fitness-related traits that were generated by differences in the rank order of plant lines among environments. Overall, our results suggest that the expression of genotypic variation and selection on nodulation differ across environments. In the field, significant rank-order changes for plant fitness potentially help maintain genetic variation in natural populations, even in the face of directional or stabilizing selection.

### Description of markdown (.md) files, relevant folders in parentheses:

1. data_setup:
    * import Simonsen & Stinchcombe's (2014) dataset (./raw_data/)
    * combine with KSR field data (./raw_data/)
    * clean up datasets and save as .Rdata files (./raw_data/dataset_cleaned/)
  
2. data_analyses_raw_means:
    * calculate raw means for each line across environments, and within each environment (./raw_means/)
    * reaction norm plots (./figures/)
    * correlation plots within and across environments (./figures/)
  
3. data_analyses_GxE: 
    * generalized linear model (GLM) framework using line and environment as a fixed effect
    * model outputs (./GxE_analyses_outputs/)
  
4. data_analyses_SxE:
    * does selection differ among environments? Options to compare:
        * standardize nodules globally, use absolute fitness
        * standardize and relativize traits globally
        * standardize and relativize traits within each environment
        * model and figure outputs (./SxE_analyses_outputs)
    * selection within each environment (./SxE_analyses_outputs)
    * selection figures (./figures/)
  
5. data_analyses_heritability:
    * linear mixed models (lmms) for each trait within each environment to calculate the total phenotypic variance (vtot), genetic variance (Vg = vcov ofline term), and heritability (Vtot/Vg)
    * model outputs (./heritability_analyses/)
  
6. data_analyses_cockerham:
    * import Vg and rg (genetic correlations) (./Cockerhams_method/)
    * functions to partition GxE into rank and variance SS
    * outputs (./Cockerhams_method/)
  
7. figure1_seq_map:
    * import sequencing data (./raw_data/)
    * make figure and combine with site map to make Figure 1 (./figures/)